### ISSUE TITLE
Any plans on supporting Windows as well?

### ISSUE THREAD

**Issue by EriKWDev** [arnemolland/crayola#1]
Electron projects usually emulates a fake Windows titlebar with html and css to make it look native. This can be seen for VSCode for example. I don't know if this could be done natively directly, but the titlebar could probably be turned off and then faked with Flutter widgets if that doesn't work.

**Comment by arnemolland** [comment]
I'll have a look at it, my initial guess is that it's possible to do natively, but if not that's a possible approach as well!

**Comment by EriKWDev** [comment]
There is a package called [bitsdojo_window](https://github.com/bitsdojo/bitsdojo_window) which implements a "fake" flutter-widget to emulate the Windows titlebar. The package is a bit un-focused though with some windowing functionality and more.

It would be nice to have a more focused package like this one xP

**Comment by arnemolland** [comment]
I've taken a look at it as well. After some research, it looks like [DWM](https://docs.microsoft.com/en-us/windows/win32/dwm/customframe) could be the way to go, but the APIs look ugly. I'll have a go when I get hold of a Windows PC later today.

**Comment by EriKWDev** [comment]
A native solution would indeed be much preferred xP That looks exactly like it!

**Comment by EriKWDev** [comment]
@arnemolland Have you had any luck with the DWM API? :)

**Comment by arnemolland** [comment]
Sorry for the late response, I haven't had the time or a Windows copy to test with as of late. I may actually check out Codespaces with a Windows image to take another look.

**Comment by arnemolland** [comment]
My thought after initially looking at this is that the most viable solution is to replace the title bar entirely with a widget.

**Comment by arnemolland** [comment]
I won't be taking this on in the near future, if anyone wants to you're welcome!
